### PR TITLE
GH-325: Initial Support for RabbitMQ Stream Plugin

### PR DESCRIPTION
**Pull request by garyrussell**
Resolves https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/325

Also tested with a Boot application.

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
LGTM, but probably need to be rebased to the latest Spring AMQP, which has just changed to `ConsumerCustomizer` contract: https://github.com/spring-projects/spring-amqp/pull/1364

**Comment by garyrussell** [comment]
It depends on when it will be merged; there is a cloud milestone next week; if this is merged before then, it must remain on milestones. Or, we can defer the merge until after the milestone.

**Comment by garyrussell** [comment]
I think @sabbyanandan is keen to get this into people's hands.

**Comment by artembilan** [comment]
Well, since that is  going to be a milestone, we are good to make this based on Spring AMQP milestone and merge before Cloud train.
I guess Spring Boot `2.6.0` is already based on Spring AMQP `2.4.0`...

**Comment by artembilan** [comment]
Looks like there is another PR for this project already based on Spring Boot 2.6: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/323

**Comment by artembilan** [comment]
Let's rebase this to the current `main` and merge!
Probably better to remove all those changes to POMs, though...

**Pull request merged**
