### PR TITLE
RequeueRejected parameter explained wrongly in README

### PR DESCRIPTION
**Pull request by chenghaoharvey**
Fixes gh-300

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@chenghaoharvey Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-rabbit&pullRequestId=301)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-rabbit&pullRequestId=301) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@chenghaoharvey Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-rabbit&pullRequestId=301)!

**Comment by chenghaoharvey** [comment]
Any response or what should i adjust for this PR?

**Comment by garyrussell** [comment]
Thanks for the contribution.

**Pull request merged**
